#!/bin/sh
set -eux
exec sudo systemd-run --unit=keycloak --uid=$(id -u) --gid=$(id -g) docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:23.0.3 start-dev
