[package]
name = "di-transaction"
version = "0.1.0"
authors = ["Yusuke Nojima <nojima@ynojima.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
anyhow = "*"
